# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2ffba19f5250e8505847aeeeb080768868c419590d8fac5c2ef44cfc5917c2317596c06e8ae19cd4b7c74dd495da7567fe953983dee11f9f5154497c7407963

test:
  secret_key_base: 5846cddcd4617605dd2c028afceb2a2b8bb7d6a3d1e5217975f1f18722330be22015993226ced211993519709dd92f06f8438b0817ffde17417bfa9381065458

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
